#!/bin/bash
set -Ceux

# コマンド実行時の第2引数以下をARGに格納
ARGS=${@:2}

case ${1} in
"install") ## install dependencies
[ -z $(which deno) ] && brew install deno
;;
"up") ## start server
deno task serve
;;
"fmt") ## format all files
deno task fmt
;;
"build") ## build for production
deno task build
;;
"help" | *)
(
echo "HELP"
echo "  COMMAND ) DESCRIPTION ) REQUIRE ) ARGS"
\grep -E "\)\ *\##" ${0}
) | column -t -s "\)"
;;
esac
